postgres:
  address: localhost:5432
  database: sample
  username: postgres
  password: postgres

redis:
  address: localhost:6379
  password:
  db: 0
  max_retries: 0
  min_retry_backoff: 0
  max_retry_backoff: 0
  dial_timeout: 0
  read_timeout: 0
  write_timeout: 0
  pool_size: 0
  pool_timeout: 0
  idle_timeout: 0
  idle_check_frequency: 0

logger:
  level: debug
  format: console
  color: true
  full_caller: true